title: Data size reduction technique for ultrafast imaging: Combining Ultrasound Localization Microscopy with Sub-Nyquist Sampling # name of the site
author: Hyojin Seong, DGIST, South Korea # name of site's author
email: shj961105@dgist.ac.kr # email of site's author
#url: https://riggraz.dev # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  This page is for Result images of Hyojin Seong's Abstract.
  It is stated that the image prohibits the unauthorized use of the judges other than for the purpose of examination.

permalink: /:slug.html

# favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
